steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/dtumlops-484220/artifacts-exercises/gcp_test_app',
    '-f',
    'simple_fastapi_app.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/dtumlops-484220/artifacts-exercises/gcp_test_app'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'gcp-test-app',
    '--image',
    'europe-west1-docker.pkg.dev/dtumlops-484220/artifacts-exercises/gcp_test_app',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
